// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi TinyUrl API Service
This is the documentation for TinyUrl API Service.<br>


    Schemes:
      http
      https
    Host: api.shortener.com
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
