// Code generated by go-swagger; DO NOT EDIT.

package url_shortener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "api_service/server/models"
)

// CreateShortenedURLOKCode is the HTTP code returned for type CreateShortenedURLOK
const CreateShortenedURLOKCode int = 200

/*CreateShortenedURLOK OK

swagger:response createShortenedUrlOK
*/
type CreateShortenedURLOK struct {

	/*
	  In: Body
	*/
	Payload *CreateShortenedURLOKBody `json:"body,omitempty"`
}

// NewCreateShortenedURLOK creates CreateShortenedURLOK with default headers values
func NewCreateShortenedURLOK() *CreateShortenedURLOK {

	return &CreateShortenedURLOK{}
}

// WithPayload adds the payload to the create shortened Url o k response
func (o *CreateShortenedURLOK) WithPayload(payload *CreateShortenedURLOKBody) *CreateShortenedURLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create shortened Url o k response
func (o *CreateShortenedURLOK) SetPayload(payload *CreateShortenedURLOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateShortenedURLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateShortenedURLBadRequestCode is the HTTP code returned for type CreateShortenedURLBadRequest
const CreateShortenedURLBadRequestCode int = 400

/*CreateShortenedURLBadRequest Bad Request

swagger:response createShortenedUrlBadRequest
*/
type CreateShortenedURLBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateShortenedURLBadRequest creates CreateShortenedURLBadRequest with default headers values
func NewCreateShortenedURLBadRequest() *CreateShortenedURLBadRequest {

	return &CreateShortenedURLBadRequest{}
}

// WithPayload adds the payload to the create shortened Url bad request response
func (o *CreateShortenedURLBadRequest) WithPayload(payload *models.Error) *CreateShortenedURLBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create shortened Url bad request response
func (o *CreateShortenedURLBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateShortenedURLBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateShortenedURLUnauthorizedCode is the HTTP code returned for type CreateShortenedURLUnauthorized
const CreateShortenedURLUnauthorizedCode int = 401

/*CreateShortenedURLUnauthorized Unauthorized

swagger:response createShortenedUrlUnauthorized
*/
type CreateShortenedURLUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateShortenedURLUnauthorized creates CreateShortenedURLUnauthorized with default headers values
func NewCreateShortenedURLUnauthorized() *CreateShortenedURLUnauthorized {

	return &CreateShortenedURLUnauthorized{}
}

// WithPayload adds the payload to the create shortened Url unauthorized response
func (o *CreateShortenedURLUnauthorized) WithPayload(payload *models.Error) *CreateShortenedURLUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create shortened Url unauthorized response
func (o *CreateShortenedURLUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateShortenedURLUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateShortenedURLConflictCode is the HTTP code returned for type CreateShortenedURLConflict
const CreateShortenedURLConflictCode int = 409

/*CreateShortenedURLConflict Conflict

swagger:response createShortenedUrlConflict
*/
type CreateShortenedURLConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateShortenedURLConflict creates CreateShortenedURLConflict with default headers values
func NewCreateShortenedURLConflict() *CreateShortenedURLConflict {

	return &CreateShortenedURLConflict{}
}

// WithPayload adds the payload to the create shortened Url conflict response
func (o *CreateShortenedURLConflict) WithPayload(payload *models.Error) *CreateShortenedURLConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create shortened Url conflict response
func (o *CreateShortenedURLConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateShortenedURLConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateShortenedURLInternalServerErrorCode is the HTTP code returned for type CreateShortenedURLInternalServerError
const CreateShortenedURLInternalServerErrorCode int = 500

/*CreateShortenedURLInternalServerError Internal server error

swagger:response createShortenedUrlInternalServerError
*/
type CreateShortenedURLInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateShortenedURLInternalServerError creates CreateShortenedURLInternalServerError with default headers values
func NewCreateShortenedURLInternalServerError() *CreateShortenedURLInternalServerError {

	return &CreateShortenedURLInternalServerError{}
}

// WithPayload adds the payload to the create shortened Url internal server error response
func (o *CreateShortenedURLInternalServerError) WithPayload(payload *models.Error) *CreateShortenedURLInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create shortened Url internal server error response
func (o *CreateShortenedURLInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateShortenedURLInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateShortenedURLDefault Unexpected error

swagger:response createShortenedUrlDefault
*/
type CreateShortenedURLDefault struct {
	_statusCode int
}

// NewCreateShortenedURLDefault creates CreateShortenedURLDefault with default headers values
func NewCreateShortenedURLDefault(code int) *CreateShortenedURLDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateShortenedURLDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create shortened Url default response
func (o *CreateShortenedURLDefault) WithStatusCode(code int) *CreateShortenedURLDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create shortened Url default response
func (o *CreateShortenedURLDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *CreateShortenedURLDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
