// Code generated by go-swagger; DO NOT EDIT.

package url_shortener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetShortenedURLParams creates a new GetShortenedURLParams object
// no default values defined in spec.
func NewGetShortenedURLParams() GetShortenedURLParams {

	return GetShortenedURLParams{}
}

// GetShortenedURLParams contains all the bound params for the get shortened Url operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetShortenedUrl
type GetShortenedURLParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*shortened URL to fetch the original URL.
	  Required: true
	  In: path
	*/
	ShortenURL int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetShortenedURLParams() beforehand.
func (o *GetShortenedURLParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rShortenURL, rhkShortenURL, _ := route.Params.GetOK("shortenUrl")
	if err := o.bindShortenURL(rShortenURL, rhkShortenURL, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindShortenURL binds and validates parameter ShortenURL from path.
func (o *GetShortenedURLParams) bindShortenURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("shortenUrl", "path", "int64", raw)
	}
	o.ShortenURL = value

	return nil
}
