// Code generated by go-swagger; DO NOT EDIT.

package url_shortener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "api_service/server/models"
)

// GetShortenedURLOKCode is the HTTP code returned for type GetShortenedURLOK
const GetShortenedURLOKCode int = 200

/*GetShortenedURLOK OK

swagger:response getShortenedUrlOK
*/
type GetShortenedURLOK struct {

	/*
	  In: Body
	*/
	Payload *GetShortenedURLOKBody `json:"body,omitempty"`
}

// NewGetShortenedURLOK creates GetShortenedURLOK with default headers values
func NewGetShortenedURLOK() *GetShortenedURLOK {

	return &GetShortenedURLOK{}
}

// WithPayload adds the payload to the get shortened Url o k response
func (o *GetShortenedURLOK) WithPayload(payload *GetShortenedURLOKBody) *GetShortenedURLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get shortened Url o k response
func (o *GetShortenedURLOK) SetPayload(payload *GetShortenedURLOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShortenedURLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShortenedURLBadRequestCode is the HTTP code returned for type GetShortenedURLBadRequest
const GetShortenedURLBadRequestCode int = 400

/*GetShortenedURLBadRequest Bad Request

swagger:response getShortenedUrlBadRequest
*/
type GetShortenedURLBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetShortenedURLBadRequest creates GetShortenedURLBadRequest with default headers values
func NewGetShortenedURLBadRequest() *GetShortenedURLBadRequest {

	return &GetShortenedURLBadRequest{}
}

// WithPayload adds the payload to the get shortened Url bad request response
func (o *GetShortenedURLBadRequest) WithPayload(payload *models.Error) *GetShortenedURLBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get shortened Url bad request response
func (o *GetShortenedURLBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShortenedURLBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShortenedURLUnauthorizedCode is the HTTP code returned for type GetShortenedURLUnauthorized
const GetShortenedURLUnauthorizedCode int = 401

/*GetShortenedURLUnauthorized Unauthorized

swagger:response getShortenedUrlUnauthorized
*/
type GetShortenedURLUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetShortenedURLUnauthorized creates GetShortenedURLUnauthorized with default headers values
func NewGetShortenedURLUnauthorized() *GetShortenedURLUnauthorized {

	return &GetShortenedURLUnauthorized{}
}

// WithPayload adds the payload to the get shortened Url unauthorized response
func (o *GetShortenedURLUnauthorized) WithPayload(payload *models.Error) *GetShortenedURLUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get shortened Url unauthorized response
func (o *GetShortenedURLUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShortenedURLUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShortenedURLNotFoundCode is the HTTP code returned for type GetShortenedURLNotFound
const GetShortenedURLNotFoundCode int = 404

/*GetShortenedURLNotFound Not found

swagger:response getShortenedUrlNotFound
*/
type GetShortenedURLNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetShortenedURLNotFound creates GetShortenedURLNotFound with default headers values
func NewGetShortenedURLNotFound() *GetShortenedURLNotFound {

	return &GetShortenedURLNotFound{}
}

// WithPayload adds the payload to the get shortened Url not found response
func (o *GetShortenedURLNotFound) WithPayload(payload *models.Error) *GetShortenedURLNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get shortened Url not found response
func (o *GetShortenedURLNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShortenedURLNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShortenedURLInternalServerErrorCode is the HTTP code returned for type GetShortenedURLInternalServerError
const GetShortenedURLInternalServerErrorCode int = 500

/*GetShortenedURLInternalServerError Internal server error

swagger:response getShortenedUrlInternalServerError
*/
type GetShortenedURLInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetShortenedURLInternalServerError creates GetShortenedURLInternalServerError with default headers values
func NewGetShortenedURLInternalServerError() *GetShortenedURLInternalServerError {

	return &GetShortenedURLInternalServerError{}
}

// WithPayload adds the payload to the get shortened Url internal server error response
func (o *GetShortenedURLInternalServerError) WithPayload(payload *models.Error) *GetShortenedURLInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get shortened Url internal server error response
func (o *GetShortenedURLInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShortenedURLInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetShortenedURLDefault Unexpected error

swagger:response getShortenedUrlDefault
*/
type GetShortenedURLDefault struct {
	_statusCode int
}

// NewGetShortenedURLDefault creates GetShortenedURLDefault with default headers values
func NewGetShortenedURLDefault(code int) *GetShortenedURLDefault {
	if code <= 0 {
		code = 500
	}

	return &GetShortenedURLDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get shortened Url default response
func (o *GetShortenedURLDefault) WithStatusCode(code int) *GetShortenedURLDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get shortened Url default response
func (o *GetShortenedURLDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetShortenedURLDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
